### PR TITLE
deploy: Add autogenerated YAML files

### PR DESCRIPTION
**Pull request by mrostecki**
Autogenerated YAML files for openSUSE and SLES12.

Signed-off-by: Michal Rostecki <mrostecki@suse.de>

### CODE REVIEW

**Comment by mrostecki** [comment]
@jordimassaguerpla Yes, I still want to include them.

If we include them in the repo, then users can execute commands like:

```
kubectl apply -f https://raw.githubusercontent.com/mrostecki/kubic-ingress-controller/master/with-rbac.yaml
```

One of my ideas for later is documenting how to deploy ingress controller without cloning the repo.

**Comment by jordimassaguerpla** [comment]
I think I've seen some projects that include packages, like rpms or .debs, but they do it differently, as they were creating file releases.

For example:

see https://github.com/NVIDIA/nvidia-docker

The refer to:

https://nvidia.github.io/nvidia-docker/gpgkey

I don't know how this is created, but looks a better option than including the autogenerated file in the git repo.

**Comment by mrostecki** [comment]
The PR is ready for review, I added instructions how to use SLES images.

**Comment by mrostecki** [comment]
@jordimassaguerpla Could you explain how example of nvidia-docker and gpgkey refers to having ready to use YAML files with different image names? Sorry, but I don't see any similarities or patterns to reuse. Is there any specific file I should look at?

BTW, if you are curious about my "inspirations" - the pattern with generating YAML files with sed and comiting them to git repo is "borrowed" from Cilium. And then you can deploy Cilium by using command `kubectl create -f http://raw.github.com/blahblah/cilium.yaml`.

**Comment by mrostecki** [comment]
I've just changed instructions to use generated YAML files from raw-githubcusercontent.com, so users don't have to clone the repo.

**Comment by jordimassaguerpla** [comment]
@mrostecki : I saw some projects using github pages to release binary builds and I thought we could release the yaml files using the same mechanism, but instead of building a binary, calling the script to autogenerate the yaml files. This way, the yaml files will be up-to-date.

However, after digging on this, IIUC we would need some sort of CI to do that (travis, circleCI) and I don't think is worth blocking this PR because of that.

Please just consider doing that as an enhancement in the future.

**Pull request merged**
